p1a:p1a.h p1a.cpp p1a.main.cpp
	g++ p1a.h p1a.cpp p1a.main.cpp -o p1a 
p1b:p1a.h p1b.cpp p1b.main.cpp
	g++ p1a.h p1b.cpp p1b.main.cpp -o p1b
bug:p1.bug.cpp p1a.h p1a.cpp
	g++ p1.bug.cpp p1a.h p1a.cpp -g -o p1.bug
	
